name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  client-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/src/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: ./client/src
      - name: Run tests
        run: npm test
        working-directory: ./client/src

  server-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/src/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: ./server/src
      - name: Run tests
        run: npm test
        working-directory: ./server/src
