name: Pinecone IAC

on:
  workflow_dispatch:

jobs:
  manage-pinecone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Install dependencies
        run: uv sync --locked
        working-directory: ./pinecone-scripts

      - name: Check for index
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: uv run python check_pinecone_index.py
        working-directory: ./pinecone-scripts

      - name: Upsert records
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: uv run python upsert_pinecone_records.py
        working-directory: ./pinecone-scripts

      - name: Test records
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: uv run python test_pinecone_records.py
        working-directory: ./pinecone-scripts
