name: Pinecone IAC

on:
  workflow_dispatch:

jobs:
  manage-pinecone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install @pinecone-database/pinecone
        working-directory: ./pinecone-scripts

      - name: Check for index
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: node check-pinecone-index.js
        working-directory: ./pinecone-scripts

      - name: Upsert records
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: node upsert-pinecone-records.js
        working-directory: ./pinecone-scripts

      - name: Test records
        env:
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        run: node test-pinecone-records.js
        working-directory: ./pinecone-scripts
